name: 'GoDiffy Visual Regression'
description: 'Upload visual regression test screenshots to GoDiffy and generate comparison reports'
author: 'GoDiffy'
branding:
  icon: 'camera'
  color: 'blue'

inputs:
  api-key:
    description: 'GoDiffy API key for authentication'
    required: true
  site-id:
    description: 'GoDiffy Site ID'
    required: true
  images-path:
    description: 'Path to directory containing screenshots'
    required: true
  base-url:
    description: 'GoDiffy API base URL'
    required: true
  baseline-branch:
    description: 'Branch to use as baseline'
    required: false
    default: 'master'
  baseline-commit:
    description: 'Commit SHA or "latest"'
    required: false
    default: 'latest'
  create-report:
    description: 'Whether to run comparisons and save as report'
    required: false
    default: 'false'
  algorithm:
    description: 'Comparison algorithm (pixelmatch or ssim)'
    required: false
    default: 'pixelmatch'
  threshold:
    description: 'Similarity threshold (0.0-1.0, where 1.0 = identical)'
    required: false
    default: '0.9'

outputs:
  total-comparisons:
    description: 'Number of images compared'
  passed-comparisons:
    description: 'Number of comparisons that passed threshold'
  failed-comparisons:
    description: 'Number of comparisons that failed threshold'
  average-similarity:
    description: 'Average similarity percentage (0-100) across all comparisons'
  report-id:
    description: 'ID of saved report (if saveReport was true)'
  report-url:
    description: 'URL to view report in GoDiffy dashboard (if generated)'

runs:
  using: 'node20'
  main: 'index.js'