name: 'GoDiffy Visual Regression'
description: 'Upload visual regression test screenshots to GoDiffy and generate comparison reports'
author: 'GoDiffy'
branding:
  icon: 'camera'
  color: 'blue'

inputs:
  api-key:
    description: 'GoDiffy API key for authentication'
    required: true
  site-id:
    description: 'GoDiffy Site ID'
    required: true
  images-path:
    description: 'Path to directory containing screenshots (not required if only running comparison or using capture-screenshots)'
    required: false
  capture-screenshots:
    description: 'Whether to capture screenshots from URLs defined in godiffy.json'
    required: false
    default: 'false'
  config-path:
    description: 'Path to godiffy.json configuration file'
    required: false
    default: './godiffy.json'
  base-url:
    description: 'GoDiffy API base URL'
    required: true
  baseline-branch:
    description: 'Branch to use as baseline'
    required: false
    default: 'master'
  baseline-commit:
    description: 'Commit SHA or "latest"'
    required: false
    default: 'latest'
  create-report:
    description: 'Whether to run comparisons and save as report'
    required: false
    default: 'false'
  algorithm:
    description: 'Comparison algorithm (pixelmatch or ssim)'
    required: false
    default: 'pixelmatch'
  threshold:
    description: 'Similarity threshold (0.0-1.0, where 1.0 = identical)'
    required: false
    default: '0.9'

outputs:
  total-comparisons:
    description: 'Number of images compared'
  passed-comparisons:
    description: 'Number of comparisons that passed threshold'
  failed-comparisons:
    description: 'Number of comparisons that failed threshold'
  average-similarity:
    description: 'Average similarity percentage (0-100) across all comparisons'
  report-id:
    description: 'ID of saved report (if saveReport was true)'
  report-url:
    description: 'URL to view report in GoDiffy dashboard (if generated)'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install --production
        if [ "${{ inputs.capture-screenshots }}" = "true" ]; then
          npx playwright install chromium --with-deps
        fi
    
    - name: Run action
      shell: bash
      env:
        INPUT_API-KEY: ${{ inputs.api-key }}
        INPUT_SITE-ID: ${{ inputs.site-id }}
        INPUT_IMAGES-PATH: ${{ inputs.images-path }}
        INPUT_CAPTURE-SCREENSHOTS: ${{ inputs.capture-screenshots }}
        INPUT_CONFIG-PATH: ${{ inputs.config-path }}
        INPUT_BASE-URL: ${{ inputs.base-url }}
        INPUT_BASELINE-BRANCH: ${{ inputs.baseline-branch }}
        INPUT_BASELINE-COMMIT: ${{ inputs.baseline-commit }}
        INPUT_CREATE-REPORT: ${{ inputs.create-report }}
        INPUT_ALGORITHM: ${{ inputs.algorithm }}
        INPUT_THRESHOLD: ${{ inputs.threshold }}
      run: node ${{ github.action_path }}/index.js